version: 0.2

env:
  variables:
    S3_BUCKET: fraud-detectml1           # ← replace
    AWS_REGION: us-east-1                     # ← replace
    FEATURE_GROUP_NAME: creditcard-fg1
    MODEL_PACKAGE_GROUP_NAME: creditcard-mpg
    ENDPOINT_NAME: creditcard-endpoint
    TRAIN_JOB_NAME: trainingjobregister
    SAGEMAKER_ROLE_ARN: arn:aws:iam::419622399030:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Starting SageMaker MLOps pipeline..."

  build:
    commands:
      - python preprocess.py
      - python feature_store.py
      - python train_xgboost.py
      - python register_model.py
      - python deploy_endpoint.py

artifacts:
  files:
    - '**/*'
